#pragma once

#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_DISPLAY_128X32
#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_BRIGHTNESS 128
#define OLED_UPDATE_INTERVAL 1000

#define WS2812_DI_PIN GP3
#define RGBLIGHT_LED_COUNT 6
#define RGBLIGHT_LIMIT_VAL 80
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT

#define RGBLIGHT_LAYERS
